name: Construir documentación
on:
  push:
    branches:
      - 'main'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container: asmilex/raytracing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile web documentation
        run: |
          cd docs
          make PANDOC_EXEC=pandoc web

      - name: Commit and push index.html
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/index.html
          git commit -m "Actualizado github-pages"
          git push
