name: Construir documentación
on:
  push:
    branches:
      - 'main'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container: asmilex/raytracing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile web documentation
        run: |
          cd docs
          make PANDOC_EXEC=pandoc web

      - name: Commit index.html
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "noreply@example.com"
          git add docs/index.html
          git commit -m "[:notebook:] Actualizando Github Pages"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: ${{ github.ref }}
