name: Construir documentación
on:
  push:
    branches:
      - 'main'

jobs:
  check-files:
    name: Check if .md have been updated
    runs-on: ubuntu-latest

    outputs:
      updated: ${{ steps.out.outputs.updated }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.1

      - name: Set output
        id: out
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
            if  [[   "$file" == *docs/chapters/*md*
                  || "$file" == *docs/chapters/*.bib*
                  ||  "$file" == *docs/Makefile*
                  ||  "$file" == *docs/headers/* ]]; then

              echo '::set-output name=updated::true'
            fi
          done


  build-web:
    name: Construir la web

    needs: check-files
    if: ${{ needs.check-files.outputs.updated }}

    runs-on: ubuntu-latest
    container: asmilex/raytracing

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile web documentation
        run: |
          cd docs
          make PANDOC_EXEC=pandoc web

      - name: Commit and push index.html
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/index.html
          git commit -m "Actualizado github-pages"
          git push
