name: Create diagram
on:
  workflow_dispatch: {}

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          max_depth: 4
          output_file: "docs/img/repo_diagram.svg"
          excluded_paths: "ignore,.github,.vscode,.vs"
